export class DetalleDocumento {
  codigoDocumento: number;
  codigoEstadoDocumento: number;
  numeroDocumentoFisico: string;
  numeroExpediente: string;
  nombreDocumento: string;
  contenidoDocumento: string;
  numeroPaginas: number;
  tieneCaducidad: number;
  tieneVencimiento: number;
  fechaDocumento: string;
  fechaRecepcion: string;
  fechaCaducidad: string;
  fechaVencimiento: string;
  codigoTipoRecepcionDocumento: number;
  codigoRemitenteDocumento: number;
  codigoTipoDocumento: number;
  codigoEmpresa: number;
  codigoSucursal: number;
  codigoArea: number;
  loginUsuarioDestino: string;
  nombreTipoDocumento: string;
  nombreEstadoDocumento: string;
  nombreRemitenteDocumento: string;
  nombreTipoRecepcion: string;
  estadoAtendido: string;
  mesaPartes?: string;
  constructor() {
    this.codigoDocumento = 0;
    this.codigoEstadoDocumento = 0;
    this.numeroDocumentoFisico = '';
    this.numeroExpediente = '';
    this.nombreDocumento = '';
    this.contenidoDocumento = '';
    this.numeroPaginas = 0;
    this.tieneCaducidad = 0;
    this.tieneVencimiento = 0;
    this.fechaDocumento = '';
    this.fechaRecepcion = '';
    this.fechaCaducidad = '';
    this.fechaVencimiento = '';
    this.codigoTipoRecepcionDocumento = 0;
    this.codigoRemitenteDocumento = 0;
    this.codigoTipoDocumento = 0;
    this.codigoEmpresa = 0;
    this.codigoSucursal = 0;
    this.codigoArea = 0;
    this.loginUsuarioDestino = '';
    this.nombreTipoDocumento = '';
    this.nombreEstadoDocumento = '';
    this.nombreRemitenteDocumento = '';
    this.nombreTipoRecepcion = '';
    this.estadoAtendido = '';
    this.mesaPartes = '';
  }
}
